/*
Name: band_pass.h
* 
Authorship:
EECS 452 W26 - Audio Spatialization
Written by Alex Shamoun
*

Description:

This is a basic band pass filter which is being used to emulate the effect of a head related transfer function (HRTF)
  for the spatialization tag project. The filter coefficients were generated using MATLAB's Filter Design and Analysis Tool,
  and are designed to allow frequencies in a specific range to pass through while attenuating frequencies outside that range. 
  This helps to create a more realistic spatial audio experience by simulating how sound waves interact with the human head and ears.

*/


/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 24-Mar-2026 16:53:47
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2024b.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */


 
#define BPL 100
int16_t BP[100] = {
     -228,   -405,   -351,   -125,      8,   -117,   -368,   -454,   -269,
      -24,    -10,   -261,   -493,   -432,   -137,     49,   -106,   -440,
     -566,   -322,     20,     54,   -287,   -621,   -547,   -125,    162,
      -48,   -548,   -758,   -396,    155,    239,   -305,   -886,   -792,
      -45,    524,    171,   -829,  -1339,   -597,    752,   1121,   -314,
    -2350,  -2462,    880,   6409,  10659,  10659,   6409,    880,  -2462,
    -2350,   -314,   1121,    752,   -597,  -1339,   -829,    171,    524,
      -45,   -792,   -886,   -305,    239,    155,   -396,   -758,   -548,
      -48,    162,   -125,   -547,   -621,   -287,     54,     20,   -322,
     -566,   -440,   -106,     49,   -137,   -432,   -493,   -261,    -10,
      -24,   -269,   -454,   -368,   -117,      8,   -125,   -351,   -405,
     -228
};
