/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
 * Generated on: 02-Feb-2026 22:51:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 100
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include <stdint.h>



/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2024b.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define LPL 100
int16_t LP[100] = {
        4,     -1,     -2,     -4,     -7,    -11,    -15,    -19,    -22,
      -24,    -24,    -21,    -14,     -4,     10,     27,     47,     68,
       88,    105,    117,    122,    116,     98,     67,     22,    -35,
     -101,   -174,   -248,   -317,   -373,   -411,   -421,   -399,   -337,
     -232,    -84,    109,    341,    608,    900,   1207,   1516,   1815,
     2089,   2326,   2515,   2646,   2714,   2714,   2646,   2515,   2326,
     2089,   1815,   1516,   1207,    900,    608,    341,    109,    -84,
     -232,   -337,   -399,   -421,   -411,   -373,   -317,   -248,   -174,
     -101,    -35,     22,     67,     98,    116,    122,    117,    105,
       88,     68,     47,     27,     10,     -4,    -14,    -21,    -24,
      -24,    -22,    -19,    -15,    -11,     -7,     -4,     -2,     -1,
        4
};
